universe = vanilla
executable = run_vh2024.sh
should_transfer_files = YES
transfer_executable = YES
when_to_transfer_output = ON_EXIT
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
notification = never

GRIDPACK_XROOTD_BASE = root://eoscms.cern.ch:1094//eos/cms/store/group/phys_btag/spmondal/bb_cc_variableM/gridpacks_2024
OUTPUT_XROOTD_BASE = root://eoscms.cern.ch:1094//eos/cms/store/group/phys_btag/spmondal/bb_cc_variableM/2024

transfer_input_files = x509up_user.pem,cmsDrive_commands_2024.sh,ZHjj.py,custom_btv_overlay.py,mass_selector.py,mass_weights_2024.tsv
arguments = $(ClusterId) $(ProcId) 643 $(OUTPUT_XROOTD_BASE) $(GRIDPACK_XROOTD_BASE)

request_cpus = 1
request_disk = 30GB
MY.WantOS = "el8"
+JobFlavour = "testmatch"

output = logs/condor_$(ClusterId).$(ProcId).out
error = logs/condor_$(ClusterId).$(ProcId).err
log = logs/condor_$(ClusterId).log

queue 933
